import pandas as pd

# Read the CSV file
data = pd.read_csv('orders.csv')

# Convert order_date column to datetime type
data['order_date'] = pd.to_datetime(data['order_date'])

# Compute total revenue generated by the online store for each month
data['month'] = data['order_date'].dt.to_period('M')
monthly_revenue = data.groupby('month')['product_price'].sum()

# Compute total revenue generated by each product
product_revenue = data.groupby('product_name')['product_price'].sum()

# Compute total revenue generated by each customer
customer_revenue = data.groupby('customer_id')['product_price'].sum()

# Identify the top 10 customers by revenue generated
top_customers = customer_revenue.nlargest(10)

# Print the results
print("Total revenue generated by the online store for each month:")
print(monthly_revenue)
print("\nTotal revenue generated by each product:")
print(product_revenue)
print("\nTotal revenue generated by each customer:")
print(customer_revenue)
print("\nTop 10 customers by revenue generated:")
print(top_customers)